name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: Prettier
        uses: CultureHQ/actions-yarn@master
        with:
          args: ci:prettier
      - name: Lint
        uses: CultureHQ/actions-yarn@master
        with:
          args: lint
      - name: Test
        uses: CultureHQ/actions-yarn@master
        with:
          args: test
      - name: Build
        uses: CultureHQ/actions-yarn@master
        with:
          args: build
      - name: Save app
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Use app
        uses: actions/download-artifact@v2
        with:
          name: app
          path: build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project mobile-framework-recommender
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
