name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn ci:prettier
      - run: yarn lint
      - run: yarn test
      - run: yarn build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: yarn install --production --non-interactive --no-progress
      - run: yarn build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project arduino-remote
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
